namespace BSGO_Server
{
    internal enum ShopItemType
    {
        None,
        Resource,
        Augment,
        Round,
        Flare,
        Mine,
        Missile,
        Power,
        Repair,
        PointDefense,
        Flak,
        JumpTargetTransponder,
        Junk,
        Radio,
        TechAnalysis,
        Weapon,
        Computer,
        Hull,
        Engine,
        ShipPaint,
        Avionics,
        StarterKit,
        Torpedo,
        Ship,
        MetalPlate,
        AntiCapitalMissile,
        RadiationControl,
        Unknown
    }
}
